openapi: 3.0.0
info:
  title: Chance Parts API
  version: "1.2.0"
servers:
  - url: https://raw.githubusercontent.com/laly100/chance-feed/main

paths:
  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        "200":
          description: OK
          content: { text/plain: { schema: { type: string } } }

  /parts/index.json:
    get:
      operationId: getManifest
      summary: Manifest (ordine VECHI→NOU + mini)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Manifest" }

  /{file}:
    get:
      operationId: getCsvFile
      summary: Descarcă un CSV (chanceX.csv, chance.csv sau mini/latest_*.csv)
      parameters:
        - in: path
          name: file
          required: true
          schema: { type: string, example: "mini/latest_1000.csv" }
      responses:
        "200":
          description: CSV
          content: { text/csv: { schema: { type: string } } }

components:
  schemas:
    Manifest:
      type: object
      required: [schema, order, header]
      properties:
        schema: { type: string, example: "1.2" }
        order:
          type: array
          description: Fișiere principale (VECHI→NOU)
          items: { type: string, example: "chance3.csv" }
        header:
          type: array
          items: { type: string }
          example: ["תאריך","הגרלה","תלתן","יהלום","לב","עלה"]
        mini:
          type: object
          description: Fișiere mici pentru ultimele extrageri
          properties:
            latest_1000: { type: string, example: "mini/latest_1000.csv" }
            latest_2000: { type: string, example: "mini/latest_2000.csv" }
