openapi: 3.0.0
info:
  title: Chance Parts API
  version: "1.0.0"
  description: Manifest + fișiere CSV paginate (10.000 rânduri) pentru TOT istoricul.

servers:
  - url: https://raw.githubusercontent.com/laly100/chance-feed/main

paths:
  /parts/index.json:
    get:
      operationId: getManifest
      summary: Manifestul (ordinea vechi→nou)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { type: object }

  /{file}:
    get:
      operationId: getCsvPart
      summary: Descarcă un fișier CSV (chance0.csv … chanceX.csv)
      parameters:
        - in: path
          name: file
          required: true
          schema:
            type: string
            example: chance0.csv
      responses:
        "200":
          description: OK
          content:
            text/csv:
              schema: { type: string }
        "404":
          description: Not found
